// src/react/FiEyesUIWavyText.tsx
import React, { useEffect, useRef } from 'react';

export interface FiEyesUIWavyTextProps {
  text?: string;
  fontSize?: string;
  animationDuration?: number;
  waveHeight?: number;
  delayMultiplier?: number;
  autoPlay?: boolean;
  repeatInterval?: number;
  onAnimationComplete?: () => void;
  onAnimationStart?: () => void;
  className?: string;
  style?: React.CSSProperties;
}

export const FiEyesUIWavyText: React.FC<FiEyesUIWavyTextProps> = ({
  text = 'Welcome To Finches Eyes UI Components',
  fontSize = '2em',
  animationDuration = 1.5,
  waveHeight = 20,
  delayMultiplier = 0.1,
  autoPlay = true,
  repeatInterval = 0,
  onAnimationComplete,
  onAnimationStart,
  className = '',
  style = {}
}) => {
  const containerRef = useRef<HTMLDivElement>(null);
  const animationRef = useRef<number | null>(null);

  const fiEyesUIStartWavyAnimation = () => {
    if (!containerRef.current) return;

    const container = containerRef.current;
    const spans = container.querySelectorAll('.fiEyesUI-wavy-text-span');
    
    spans.forEach((span, index) => {
      const element = span as HTMLElement;
      element.style.setProperty('--i', index.toString());
      element.style.animationDelay = `${delayMultiplier * index}s`;
      element.style.animationDuration = `${animationDuration}s`;
    });

    if (onAnimationStart) {
      onAnimationStart();
    }

    if (repeatInterval > 0) {
      animationRef.current = window.setTimeout(() => {
        fiEyesUIStartWavyAnimation();
      }, repeatInterval * 1000);
    }
  };

  const fiEyesUIStopWavyAnimation = () => {
    if (animationRef.current) {
      clearTimeout(animationRef.current);
      animationRef.current = null;
    }
  };

  useEffect(() => {
    if (autoPlay) {
      fiEyesUIStartWavyAnimation();
    }

    return () => {
      fiEyesUIStopWavyAnimation();
    };
  }, [autoPlay, repeatInterval]);

  useEffect(() => {
    const handleAnimationEnd = () => {
      if (onAnimationComplete) {
        onAnimationComplete();
      }
    };

    const spans = containerRef.current?.querySelectorAll('.fiEyesUI-wavy-text-span');
    spans?.forEach(span => {
      span.addEventListener('animationend', handleAnimationEnd);
    });

    return () => {
      spans?.forEach(span => {
        span.removeEventListener('animationend', handleAnimationEnd);
      });
    };
  }, [onAnimationComplete]);

  const fiEyesUIRenderText = () => {
    return text.split('').map((char, index) => (
      <span
        key={index}
        className="fiEyesUI-wavy-text-span"
        style={{
          '--i': index,
          animationDelay: `${delayMultiplier * index}s`,
          animationDuration: `${animationDuration}s`
        } as React.CSSProperties}
      >
        {char === ' ' ? '\u00A0' : char}
      </span>
    ));
  };

  return (
    <>
      <style dangerouslySetInnerHTML={{
        __html: `
          .fiEyesUI-wavy-text-container {
            position: relative;
            display: inline-block;
            background-color: #000000;
            color: #ffffff;
            font-family: 'Orbitron', sans-serif;
            font-size: ${fontSize};
            text-transform: uppercase;
            letter-spacing: 0.1em;
          }
          
          .fiEyesUI-wavy-text-span {
            position: relative;
            display: inline-block;
            color: #ffffff;
            animation: fiEyesUI-wavy-animate ${animationDuration}s ease-in-out infinite;
            animation-delay: calc(${delayMultiplier}s * var(--i));
          }
          
          @keyframes fiEyesUI-wavy-animate {
            0%, 100% {
              transform: translateY(0px);
            }
            20% {
              transform: translateY(-${waveHeight}px);
            }
            40% {
              transform: translateY(0px);
            }
          }
        `
      }} />
      <div
        ref={containerRef}
        className={`fiEyesUI-wavy-text-container ${className}`}
        style={{
          fontSize,
          ...style
        }}
      >
        {fiEyesUIRenderText()}
      </div>
    </>
  );
};

export default FiEyesUIWavyText;

// src/vue/FiEyesUIWavyText.tsx
import { defineComponent, ref, onMounted, onUnmounted, watch, PropType } from 'vue';

export interface FiEyesUIWavyTextProps {
  text?: string;
  fontSize?: string;
  animationDuration?: number;
  waveHeight?: number;
  delayMultiplier?: number;
  autoPlay?: boolean;
  repeatInterval?: number;
  className?: string;
  style?: Record<string, any>;
}

export const FiEyesUIWavyText = defineComponent({
  name: 'FiEyesUIWavyText',
  props: {
    text: {
      type: String,
      default: 'Welcome To Finches Eyes UI Components'
    },
    fontSize: {
      type: String,
      default: '2em'
    },
    animationDuration: {
      type: Number,
      default: 1.5
    },
    waveHeight: {
      type: Number,
      default: 20
    },
    delayMultiplier: {
      type: Number,
      default: 0.1
    },
    autoPlay: {
      type: Boolean,
      default: true
    },
    repeatInterval: {
      type: Number,
      default: 0
    },
    className: {
      type: String,
      default: ''
    },
    style: {
      type: Object as PropType<Record<string, any>>,
      default: () => ({})
    }
  },
  emits: ['animationComplete', 'animationStart'],
  setup(props: FiEyesUIWavyTextProps, { emit }) {
    const containerRef = ref<HTMLDivElement | null>(null);
    const animationTimeout = ref<number | null>(null);

    const fiEyesUIStartWavyAnimation = () => {
      if (!containerRef.value) return;

      const spans = containerRef.value.querySelectorAll('.fiEyesUI-wavy-text-span');
      
      spans.forEach((span, index) => {
        const element = span as HTMLElement;
        element.style.setProperty('--i', index.toString());
        element.style.animationDelay = `${props.delayMultiplier * index}s`;
        element.style.animationDuration = `${props.animationDuration}s`;
      });

      emit('animationStart');

      if (props.repeatInterval > 0) {
        animationTimeout.value = window.setTimeout(() => {
          fiEyesUIStartWavyAnimation();
        }, props.repeatInterval * 1000);
      }
    };

    const fiEyesUIStopWavyAnimation = () => {
      if (animationTimeout.value) {
        clearTimeout(animationTimeout.value);
        animationTimeout.value = null;
      }
    };

    const fiEyesUIRenderText = () => {
      return props.text.split('').map((char, index) => (
        <span
          key={index}
          className="fiEyesUI-wavy-text-span"
          style={{
            '--i': index,
            animationDelay: `${props.delayMultiplier * index}s`,
            animationDuration: `${props.animationDuration}s`
          }}
        >
          {char === ' ' ? '\u00A0' : char}
        </span>
      ));
    };

    onMounted(() => {
      if (props.autoPlay) {
        fiEyesUIStartWavyAnimation();
      }
    });

    onUnmounted(() => {
      fiEyesUIStopWavyAnimation();
    });

    watch(() => props.autoPlay, (newVal) => {
      if (newVal) {
        fiEyesUIStartWavyAnimation();
      } else {
        fiEyesUIStopWavyAnimation();
      }
    });

    return () => (
      <>
        <style dangerouslySetInnerHTML={{
          __html: `
            .fiEyesUI-wavy-text-container {
              position: relative;
              display: inline-block;
              background-color: #000000;
              color: #ffffff;
              font-family: 'Orbitron', sans-serif;
              font-size: ${props.fontSize};
              text-transform: uppercase;
              letter-spacing: 0.1em;
            }
            
            .fiEyesUI-wavy-text-span {
              position: relative;
              display: inline-block;
              color: #ffffff;
              animation: fiEyesUI-wavy-animate ${props.animationDuration}s ease-in-out infinite;
              animation-delay: calc(${props.delayMultiplier}s * var(--i));
            }
            
            @keyframes fiEyesUI-wavy-animate {
              0%, 100% {
                transform: translateY(0px);
              }
              20% {
                transform: translateY(-${props.waveHeight}px);
              }
              40% {
                transform: translateY(0px);
              }
            }
          `
        }} />
        <div
          ref={containerRef}
          className={`fiEyesUI-wavy-text-container ${props.className}`}
          style={{
            fontSize: props.fontSize,
            ...props.style
          }}
        >
          {fiEyesUIRenderText()}
        </div>
      </>
    );
  }
});

export default FiEyesUIWavyText;
