// src/angular/fiEyesUI-wavyText.component.ts
import { Component, Input, Output, EventEmitter, ElementRef, OnInit, OnDestroy, ViewChild, AfterViewInit } from '@angular/core';

export interface FiEyesUIWavyTextConfig {
  text?: string;
  fontSize?: string;
  animationDuration?: number;
  waveHeight?: number;
  delayMultiplier?: number;
  autoPlay?: boolean;
  repeatInterval?: number;
}

@Component({
  selector: 'fiEyesUI-wavy-text',
  template: `
    <div 
      #container
      class="fiEyesUI-wavy-text-container"
      [style.font-size]="config.fontSize || '2em'"
      [style]="customStyle"
    >
      <span
        *ngFor="let char of textChars; let i = index"
        class="fiEyesUI-wavy-text-span"
        [style.--i]="i"
        [style.animation-delay]="(config.delayMultiplier || 0.1) * i + 's'"
        [style.animation-duration]="(config.animationDuration || 1.5) + 's'"
      >
        {{ char === ' ' ? '\u00A0' : char }}
      </span>
    </div>
  `,
  styles: [`
    .fiEyesUI-wavy-text-container {
      position: relative;
      display: inline-block;
      background-color: #000000;
      color: #ffffff;
      font-family: 'Orbitron', sans-serif;
      text-transform: uppercase;
      letter-spacing: 0.1em;
    }
    
    .fiEyesUI-wavy-text-span {
      position: relative;
      display: inline-block;
      color: #ffffff;
      animation: fiEyesUI-wavy-animate 1.5s ease-in-out infinite;
    }
    
    @keyframes fiEyesUI-wavy-animate {
      0%, 100% {
        transform: translateY(0px);
      }
      20% {
        transform: translateY(-20px);
      }
      40% {
        transform: translateY(0px);
      }
    }
  `]
})
export class FiEyesUIWavyTextComponent implements OnInit, AfterViewInit, OnDestroy {
  @Input() config: FiEyesUIWavyTextConfig = {};
  @Input() customStyle: string = '';
  @Output() animationComplete = new EventEmitter<void>();
  @Output() animationStart = new EventEmitter<void>();

  @ViewChild('container', { static: false }) containerRef!: ElementRef<HTMLDivElement>;

  textChars: string[] = [];
  private animationTimeout: number | null = null;

  ngOnInit() {
    this.textChars = (this.config.text || 'Welcome To Finches Eyes UI Components').split('');
  }

  ngAfterViewInit() {
    if (this.config.autoPlay !== false) {
      this.fiEyesUIStartWavyAnimation();
    }
  }

  ngOnDestroy() {
    this.fiEyesUIStopWavyAnimation();
  }

  fiEyesUIStartWavyAnimation() {
    if (!this.containerRef?.nativeElement) return;

    const spans = this.containerRef.nativeElement.querySelectorAll('.fiEyesUI-wavy-text-span');
    
    spans.forEach((span, index) => {
      const element = span as HTMLElement;
      element.style.setProperty('--i', index.toString());
      element.style.animationDelay = `${(this.config.delayMultiplier || 0.1) * index}s`;
      element.style.animationDuration = `${this.config.animationDuration || 1.5}s`;
    });

    this.animationStart.emit();

    if (this.config.repeatInterval && this.config.repeatInterval > 0) {
      this.animationTimeout = window.setTimeout(() => {
        this.fiEyesUIStartWavyAnimation();
      }, this.config.repeatInterval * 1000);
    }
  }

  fiEyesUIStopWavyAnimation() {
    if (this.animationTimeout) {
      clearTimeout(this.animationTimeout);
      this.animationTimeout = null;
    }
  }

  fiEyesUIResetAnimation() {
    this.fiEyesUIStopWavyAnimation();
    setTimeout(() => {
      this.fiEyesUIStartWavyAnimation();
    }, 100);
  }
}

// src/vue/FiEyesUIWavyText.tsx
import { defineComponent, ref, onMounted, onUnmounted, watch, PropType } from 'vue';

export interface FiEyesUIWavyTextProps {
  text?: string;
  fontSize?: string;
  animationDuration?: number;
  waveHeight?: number;
  delayMultiplier?: number;
  autoPlay?: boolean;
  repeatInterval?: number;
  className?: string;
  style?: Record<string, any>;
}

export const FiEyesUIWavyText = defineComponent({
  name: 'FiEyesUIWavyText',
  props: {
    text: {
      type: String,
      default: 'Welcome To Finches Eyes UI Components'
    },
    fontSize: {
      type: String,
      default: '2em'
    },
    animationDuration: {
      type: Number,
      default: 1.5
    },
    waveHeight: {
      type: Number,
      default: 20
    },
    delayMultiplier: {
      type: Number,
      default: 0.1
    },
    autoPlay: {
      type: Boolean,
      default: true
    },
    repeatInterval: {
      type: Number,
      default: 0
    },
    className: {
      type: String,
      default: ''
    },
    style: {
      type: Object as PropType<Record<string, any>>,
      default: () => ({})
    }
  },
  emits: ['animationComplete', 'animationStart'],
  setup(props: FiEyesUIWavyTextProps, { emit }) {
    const containerRef = ref<HTMLDivElement | null>(null);
    const animationTimeout = ref<number | null>(null);

    const fiEyesUIStartWavyAnimation = () => {
      if (!containerRef.value) return;

      const spans = containerRef.value.querySelectorAll('.fiEyesUI-wavy-text-span');
      
      spans.forEach((span, index) => {
        const element = span as HTMLElement;
        element.style.setProperty('--i', index.toString());
        element.style.animationDelay = `${props.delayMultiplier * index}s`;
        element.style.animationDuration = `${props.animationDuration}s`;
      });

      emit('animationStart');

      if (props.repeatInterval > 0) {
        animationTimeout.value = window.setTimeout(() => {
          fiEyesUIStartWavyAnimation();
        }, props.repeatInterval * 1000);
      }
    };

    const fiEyesUIStopWavyAnimation = () => {
      if (animationTimeout.value) {
        clearTimeout(animationTimeout.value);
        animationTimeout.value = null;
      }
    };

    const fiEyesUIRenderText = () => {
      return props.text.split('').map((char, index) => (
        <span
          key={index}
          className="fiEyesUI-wavy-text-span"
          style={{
            '--i': index,
            animationDelay: `${props.delayMultiplier * index}s`,
            animationDuration: `${props.animationDuration}s`
          }}
        >
          {char === ' ' ? '\u00A0' : char}
        </span>
      ));
    };

    onMounted(() => {
      if (props.autoPlay) {
        fiEyesUIStartWavyAnimation();
      }
    });

    onUnmounted(() => {
      fiEyesUIStopWavyAnimation();
    });

    watch(() => props.autoPlay, (newVal) => {
      if (newVal) {
        fiEyesUIStartWavyAnimation();
      } else {
        fiEyesUIStopWavyAnimation();
      }
    });

    return () => (
      <>
        <style dangerouslySetInnerHTML={{
          __html: `
            .fiEyesUI-wavy-text-container {
              position: relative;
              display: inline-block;
              background-color: #000000;
              color: #ffffff;
              font-family: 'Orbitron', sans-serif;
              font-size: ${props.fontSize};
              text-transform: uppercase;
              letter-spacing: 0.1em;
            }
            
            .fiEyesUI-wavy-text-span {
              position: relative;
              display: inline-block;
              color: #ffffff;
              animation: fiEyesUI-wavy-animate ${props.animationDuration}s ease-in-out infinite;
              animation-delay: calc(${props.delayMultiplier}s * var(--i));
            }
            
            @keyframes fiEyesUI-wavy-animate {
              0%, 100% {
                transform: translateY(0px);
              }
              20% {
                transform: translateY(-${props.waveHeight}px);
              }
              40% {
                transform: translateY(0px);
              }
            }
          `
        }} />
        <div
          ref={containerRef}
          className={`fiEyesUI-wavy-text-container ${props.className}`}
          style={{
            fontSize: props.fontSize,
            ...props.style
          }}
        >
          {fiEyesUIRenderText()}
        </div>
      </>
    );
  }
});

export default FiEyesUIWavyText;
